[pyfile, _mysql_exceptions.py]
